{
    "text": "vul_name : python backports ssl_match_hostname Resource Exhaustion 0day ， vul_cve : CVE-2013-2098 , CVE-2013-2099 ， vul_poc : A denial of service flaw was found in the way python-backports-ssl_match_hostname ,  ， an implementation that brings the ssl.match_hostname (  ) function from Python 3.2 to ， users of earlier versions of Python , performed matching of the certificate's name ， in the case it contained many ' * ' wildcard characters. A remote attacker , able to ， obtain valid certificate [  *  ] with its name containing a lot of ' * ' wildcard characters ,  ， could use this flaw to cause denial of service ( excessive CPU time consumption ) by ， issuing request to validate that certificate for / in an application using the ， python-backports-ssl_match_hostname functionality. ， Upstream bug report ( no patch yet )  :  ，  [ 1 ]  ，  [ 2 ]  ， Credit : Issue was found by Florian Weimer of Red Hat Product Security Team",
    "time": "2013-05-15 / 2013-05-17"
}