{
    "text": "vul_url : ， vul_name : CPython hash secret can be recoved remotely ， vul_date : 2013.12.10 ， vul_credit_name : Nick Coghlan ， vul_risk : Medium ， vul_local : No ， vul_remote : Yes ， vul_cve : CVE-2013-7040 ， vul_cwe : ， vul_poc : Software: CPython ， Vendor: Python Software Foundation ， Vulnerability: remote target-specific CPU usage DOS ， This is a followup to CVE-2012-1150 (hash table collision CPU usage DOS ， in CPython) ， points out that the hash secret in ， CPython can be recovered remotely, so while the original fix addressed ， the \"blind DOS\" problem (of being able to DOS any Python based service ， with a single prepared payload), it didn't completely eliminate the ， potential for remote DOS attacks based on hash collisions. ， ( has the details) ， Python 3.4+ will use SipHash by default ， ( which should resolve the ， vulnerability completely. ， Regards, ， Nick. ， Nick Coghlan"
}