{
    "text": "Subject : Django Security Releases for CVE-2020-24583 & CVE-2020-24584 :  ， permissions on intermediate-level directories on Python 3.7+ ， In accordance with `our security release policy <https : /docs.djangoproject.com/en/dev/internals/security/>`_ , the Django team is issuing ， `Django 3.1.1 <https : /docs.djangoproject.com/en/dev/releases/3.1.1/>`_ ,  ， `Django 3.0.10 <https : /docs.djangoproject.com/en/dev/releases/3.0.10/>`_ and ， `Django 2.2.16 <https : /docs.djangoproject.com/en/dev/releases/2.2.16/>`_. ， These releases address the security issue detailed below. We encourage all users of Django to upgrade as soon as possible. ， CVE-2020-24583 : Incorrect permissions on intermediate-level directories on Python 3.7+ ， On Python 3.7+ , `FILE_UPLOAD_DIRECTORY_PERMISSIONS` mode was not ， applied to intermediate-level directories created in the process of uploading ， files and to intermediate-level collected static directories when using the ， `collectstatic` management command. ， You should review and manually fix permissions on existing intermediate-level ， directories. ， CVE-2020-24584 : Permission escalation in intermediate-level directories of the file system cache on Python 3.7+ ， On Python 3.7+ , the intermediate-level directories of the file system cache had ， the system's standard umask rather than `0o077` ( no group or others ， permissions ) . ， Affected supported versions ，  * Django master branch ，  * Django 3.1 ，  * Django 3.0 ，  * Django 2.2",
    "time": "Tue, 1 Sep 2020 11:23:07 +0200"
}