{
    "text": "Subject : Django CVE-2022-41323 : Potential denial-of-service vulnerability in ， internationalized URLs ， Django security releases issued : 4.1.2 , 4.0.8 , and 3.2.16 ， https : /www.djangoproject.com/weblog/2022/oct/04/security-releases/ ， In accordance with `our security release policy ， <https : /docs.djangoproject.com/en/dev/internals/security/>`_ , the Django ， team ， is issuing ， `Django 4.1.2 <https : /docs.djangoproject.com/en/dev/releases/4.1.2/>`_ ,  ， `Django 4.0.8 <https : /docs.djangoproject.com/en/dev/releases/4.0.8/>`_ , and ， `Django 3.2.16 <https : /docs.djangoproject.com/en/dev/releases/3.2.16/>`_. ， These releases addresses the security issue detailed below. We encourage all ， users of Django to upgrade as soon as possible. ， CVE-2022-41323 : Potential denial-of-service vulnerability in ， internationalized URLs ， Internationalized URLs were subject to potential denial of service attack ， via ， the locale parameter. This is now escaped to avoid this possibility. ， This issue has medium severity , according to the Django security policy. ， Thanks to Benjamin Balder Bach for the report. ， Affected supported versions ，  * Django main branch ，  * Django 4.1 ，  * Django 4.0 ，  * Django 3.2",
    "time": "Tue, 4 Oct 2022 10:03:56 +0200"
}